python multigpu_train.py \
--gpu_list=$1 \
--input_size=512 \
--batch_size_per_gpu=14 \
--checkpoint_path=brand_sotd/ \
--text_scale=512 \
--training_data_path=$2 \
--geometry=RBOX \
--learning_rate=0.0001 \
--num_readers=24 \
--pretrained_model_path=pretrained_model/resnet_v1_50.ckpt
